DjangoHotel/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('hotel.urls')),
    path('', include("contact.urls")),
    path('accounts/', include('allauth.urls')),
]

contact/urls.py
from django.contrib import admin
from django.urls import path

from .views import contactView, successView

urlpatterns = [
    path("contact/", contactView, name="contact"),
    path("success/", successView, name="success"),
]

hotel/urls.py
from django.urls import path
from .views import (RoomListView,
                    BookingListView,
                    RoomDetailView,
                    CancelBookingView)

app_name = 'hotel'

urlpatterns = [
    path('', RoomListView, name='RoomListView'),
    # path('room_list/', RoomListView, name='RoomListView'),
    path('booking_list/', BookingListView.as_view(), name='BookingListView'),
    path('room/<category>', RoomDetailView.as_view(), name='RoomDetailView'),
    path('booking/cancel/<pk>', CancelBookingView.as_view(),
         name='CancelBookingView')
]

contact/models.py
from django.db import models

# Create your models here.

hotel/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse_lazy
from cloudinary.models import CloudinaryField

# Create your models here.


class Room(models.Model):
    ROOM_CATEGORIES = (
        ('LUX', 'LUXURY'),
        ('DUB', 'DUBBLE'),
        ('SIN', 'SINGAL'),
    )
    number = models.IntegerField()
    category = models.CharField(max_length=3, choices=ROOM_CATEGORIES)
    beds = models.IntegerField()
    capacity = models.IntegerField()

    def __str__(self):
        return (f'{self.number}. {self.category} with {self.beds} bed(s) for {self.capacity} people')


class Booking(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    check_in = models.DateTimeField()
    check_out = models.DateTimeField()

    def __str__(self):
        return f'{self.user} has booked {self.room} from {self.check_in} to {self.check_out}'

    def get_room_category(self):
        room_categories = dict(self.room.ROOM_CATEGORIES)
        room_category = room_categories.get(self.room.category)
        return room_category

    def get_cancel_booking_url(self):
        return reverse_lazy('hotel:CancelBookingView', args=[self.pk, ])

contact/forms.py
from django import forms


class ContactForm(forms.Form):
    from_email = forms.EmailField(required=True)
    subject = forms.CharField(required=True)
    message = forms.CharField(widget=forms.Textarea, required=True)

hotel/forms.py
from django import forms


class AvailabiltyForm(forms.Form):
    check_in = forms.DateTimeField(
        required=True, input_formats=["%Y-%m-%dT%H:%M", ])
    check_out = forms.DateTimeField(
        required=True, input_formats=["%Y-%m-%dT%H:%M", ])

contact/views.py
from django.core.mail import send_mail
from django.shortcuts import render, redirect
from .forms import ContactForm


def contactView(request):
    if request.method == "GET":
        form = ContactForm()
    else:
        form = ContactForm(request.POST)
        if form.is_valid():
            subject = form.cleaned_data["subject"]
            from_email = form.cleaned_data["from_email"]
            message = form.cleaned_data['message']
            send_mail(subject,
                      message,
                      from_email, ["admin@django-hotel.com"])
            return redirect("success")
    return render(request, "contact.html", {"form": form})


def successView(request):
    return render(request, "contact_success.html")

hotel/views.py
from django.shortcuts import render, HttpResponse
from django.views.generic import ListView, FormView, View, DeleteView
from django.urls import reverse, reverse_lazy
from .models import Room, Booking
from .forms import AvailabiltyForm

# Importing functions to shortening the code
from hotel.booking_functions.availability import check_availability
from hotel.booking_functions.get_room_cat_url_list import get_room_cat_url_list
from hotel.booking_functions.get_room_category_human_format import get_room_category_human_format
from hotel.booking_functions.get_available_rooms import get_available_rooms
from hotel.booking_functions.book_room import book_room


def RoomListView(request):
    room_category_url_list = get_room_cat_url_list()

    context = {
        'room_list': room_category_url_list,
    }
    return render(request, 'room_list_view.html', context)


class BookingListView(ListView):
    model = Booking
    template_name = 'booking_list_view.html'
    paginate_by = 5

    def get_queryset(self, *args, **kwargs):
        # Checks if the user is staff
        if self.request.user.is_staff:
            booking_list = Booking.objects.all()
            return booking_list

        # Or normal user
        else:
            booking_list = Booking.objects.filter(user=self.request.user)
            return booking_list


class RoomDetailView(View):
    def get(self, request, *args, **kwargs):
        # Get room category from kwargs
        category = self.kwargs.get('category', None)

        # Get the human readable format
        human_format_room_category = get_room_category_human_format(category)

        # Starts the empty form
        form = AvailabiltyForm()

        # Check for invalid category names
        if human_format_room_category is not None:
            context = {
                'room_category': human_format_room_category,
                'form': form,
            }
            return render(request, 'room_detail_view.html', context)
        else:
            return HttpResponse('Category does not exist')

    def post(self, request, *args, **kwargs):
        # Get room category from kwargs
        category = self.kwargs.get('category', None)

        # Gets the form thats being POST:ed
        form = AvailabiltyForm(request.POST)

        # Confirms if the form is valid and gets the cleaned data
        if form.is_valid():
            data = form.cleaned_data

        # Get the available rooms
        available_rooms = get_available_rooms(category, data['check_in'], data['check_out'])

        # Check if the room are available
        if available_rooms is not None:

            # Book the first available room in the list
            booking = book_room(request, available_rooms[0], data['check_in'], data['check_out'])
            context = {
                'booking': booking
            }
            return render(request, 'success_booking.html', context)
        else:
            context = {
                'data': data
            }
            return render(request, 'no_more_rooms.html', context)


class CancelBookingView(DeleteView):
    model = Booking
    template_name = 'booking_cancel_view.html'
    success_url = reverse_lazy('hotel:BookingListView')

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Font Awesome -->
    <script src="https://kit.fontawesome.com/b66a8a8811.js" crossorigin="anonymous"></script>

    <!-- Google fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=IM+Fell+English+SC&family=Lato&display=swap" rel="stylesheet">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <!-- Stylesheet link -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <title>Django Hotel</title>
</head>

<body>

    <div class="top-background border-bottom border-5 border-light">
    </div>
    <div class="bottom-background"></div>
    <div class="container-fluid z-index">
        <div class="row">
            <div class="col">
                <div class="container p-4">

                    <!-- Navigation -->
                    <nav class="navbar justify-content-center">
                        <ul class="nav nav-pills">
                            <li class="nav-item">
                                <a class="btn btn-primary nav-link {% if '/' == request.path %}active{% endif %}"
                                    href="{% url 'hotel:RoomListView'%}">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="btn btn-primary nav-link {% if '/contact/' == request.path %}active{% endif %}{% if '/success/' == request.path %}active{% endif %}"
                                    href="{% url 'contact'%}">Contact us</a>
                            </li>
                            {% if user.is_authenticated %}
                            <li class="nav-item mx-2">
                                <a class="btn btn-primary nav-link {% if '/booking_list/' == request.path %}active{% endif %}"
                                    href="{% url 'hotel:BookingListView' %}">View Reservations</a>
                            </li>
                            <li class="nav-item mx-2">
                                <a class="btn btn-primary nav-link {% if '/accounts/logout/' == request.path %}active{% endif %}"
                                    href="{% url 'account_logout' %}">Logout</a>
                            </li>
                            {% else %}
                            <li class="nav-item mx-2">
                                <a class="btn btn-primary nav-link {% if '/accounts/signup/' == request.path %}active{% endif %}"
                                    href="{% url 'account_signup' %}">Register</a>
                            </li>
                            <li class="nav-item mx-2">
                                <a class="btn btn-primary nav-link {% if '/accounts/login/' == request.path %}active{% endif %}"
                                    href="{% url 'account_login' %}">Login</a>
                            </li>
                            {% endif %}
                        </ul>
                    </nav>

                    <div class="mt-5">
                        {% block content %}
                        <!-- Our content will go here -->
                        {% endblock %}
                    </div>

                </div>
            </div>
            
        </div>
    </div>

    <!-- Copyright -->
    <footer class="fixed-bottom text-center mb-4 opacity-lower">
        © 2023 Copyright
        <a href="#">Jörgen Brattäng</a>
    </footer>

    <!-- Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous">
    </script>

</body>

</html>

templates/booking_cancel_view.html
{% extends 'base.html' %}
{% block content %}

<div class="container p-4">
    <div class="row">
        <form action="" method="POST">

            {% csrf_token %}
            <h2>Are you sure you want to cancel this booking?</h2>
            <ul class="list-unstyled">
                <li><h4>Details:</h4></li>
                <li>Room: {{ booking.room.number }}</li>
                <li>Category: {{ booking.get_room_category}}</li>
                <li>Booking: {{ booking }}</li>
            </ul>

            <div class="row mt-4">
                <button type="submit" class="btn btn-warning">Cancel the Booking</button>
            </div>
        </form>
    </div>
</div>

{% endblock %}

templates/booking_list_view.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
    <div class="col-12 mt-3">
        <div class="card p-4">
            <h2 class="text-center">Welcome {{ user }}</h2>
            {% if request.user.is_staff %}
            <h4 class="text-center">Here the occupied rooms the hotel</h4>
            {% else %}
            <h4 class="text-center">Here are your bookings.</h4>
            {% endif %}
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th scope="col">Suite</th>
                        <th scope="col">Name</th>
                        <th scope="col">From</th>
                        <th scope="col">To</th>
                        {% if request.user.is_staff %}
                        <th scope="col">Edit</th>
                        <th scope="col">Cancel</th>
                        {% endif %}
                    </tr>
                </thead>
                <tbody>
                    {% for booking in booking_list %}
                    <tr>
                        <th scope="row">{{ booking.get_room_category }}</th>
                        <td>{{ booking.user }}</td>
                        <td>{{ booking.check_in }}</td>
                        <td>{{ booking.check_out }}</td>
                        {% if request.user.is_staff %}
                        <td><a href="{{ booking.get_cancel_booking_url }}" class="btn btn-info">Edit Reservation</a>
                        </td>
                        <td><a href="{{ booking.get_cancel_booking_url }}" class="btn btn-warning">Cancel
                                Reservation</a></td>
                        {% endif %}
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            <!-- If more then 3 pages exists paginate them -->
            {% if is_paginated %}
            <div class="d-flex justify-content-center mt-4">
                <nav aria-label="Page navigation">
                    <ul class="pagination">

                        <!-- Goes back to the previous page -->
                        {% if page_obj.has_previous %}
                        <li><a href="?page={{ page_obj.previous_page_number }}" class="btn btn-primary">&laquo;
                                PREV
                            </a>
                        </li>
                        {% endif %}

                        <!-- Goes forward to the next page -->
                        {% if page_obj.has_next %}
                        <li><a href="?page={{ page_obj.next_page_number }}" class="btn btn-primary"> NEXT
                                &raquo;</a>
                        </li>
                        {% endif %}
                    </ul>
                </nav>
            </div>
            {% endif %}
            {% if request.user.is_staff %}
            <p class="text-center text-secondary">Be sure to delete the old onces they have been paid for and the occupaints have left the hotel.</p>
            {% else %}
            <p class="text-center text-secondary">To cancel or edit your booking reservation, please contact us and we will be happy to help you.</p>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

templates/contact.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block content %}
<div class="container">
  <div class="row justify-content-center">
    <div class="card col-4 p-4">
<h1>Contact Us</h1>
<form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="form-actions">
      <button type="submit" class="btn btn-success">Send</button>
    </div>
</form>
{% endblock %}

templates/contact_success.html
{% extends "base.html" %}
{% block content %}
<div class="container">
  <div class="row justify-content-center">
    <div class="card col-4 p-4">
      <h4>Success! Thank you for your message.</h4>
      <p class="text-secondary">We will be replaying as soon as we can!</p>
    </div>
  </div>
</div>
{% endblock %}

templates/detail.html
{% extends 'base.html' %}
{% block content %}

<div class="container-fluid">
    <div class="row vh-100">

        <!-- Image holder -->
        <div class="col-3 bg-primary">
        </div>

        <!-- Information holder -->
        <div class="col bg-secondary">
            <div class="container p-4">

                <!-- Room Details -->
                <div class="row">
                    <h4>Room Name</h4>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex, eum! Impedit itaque labore maiores
                        quibusdam error, nihil quae aperiam tempore? Nam assumenda fuga doloremque quasi excepturi omnis
                        culpa reprehenderit et.</p>
                </div>

                <!-- Room Booking Form -->
                <div class="row">
                    <form action="" method="POST">
                        <div class="row mt-2">
                            <label for="check_in">Check in: </label>
                            <input type="datetime-local" id="check_in" name="check_in">
                        </div>
                        <div class="row mt-2">
                            <label for="check_out">Check out: </label>
                            <input type="datetime-local" id="check_out" name="check_out">
                        </div>
                        <div class="row mt-4">
                            <button type="submit">Book the Room</button>
                        </div>
                    </form>
                </div>
                <div class="row"></div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Index</h1>

{% endblock %}

templates/no_more_rooms.html
{% extends 'base.html' %}
{% block content %}
<p>No more rooms between {{ data.check_in }} and {{ data.check_out }}</p>

{% endblock %}

templates/room_detail_view.html
{% extends 'base.html' %}
{% block content %}
<!-- Room Details -->
<div class="row justify-content-left">
    <div class="card p-2">
        <div class="row no-gutters">
            <div class="col-md-4">
                {% include 'room_images.html' with room_images=room_category %}
            </div>
            <div class="col-md-8">
                <div class="card-body">
                    <!-- Card Title and Price -->
                    <h4 class="card-title mt-1">{{ room_category }} Suite
                        {% include 'room_information.html' with room_information=room_category %}</h4>

                        {% if user.is_authenticated %}
                        <!-- Room Booking Form -->
                        <div class="row">
                            <form action="" method="POST">
            
                                {% csrf_token %}
            
                                <div class="row mt-2">
                                    <label for="id_check_in">Check in: </label>
                                    <input type="datetime-local" id="id_check_in" name="check_in">
                                </div>
                                <div class="row mt-2">
                                    <label for="id_check_out">Check out: </label>
                                    <input type="datetime-local" id="id_check_out" name="check_out">
                                </div>
                                <div class="row mt-4">
                                    <button type="submit" class="btn btn-success">Book the Room</button>
                                </div>
                            </form>
                        </div>
                        {% else %}
                        <div class="row">
                            <p>To book this suite, you need to <a href="{% url 'account_login' %}">Login</a></p>
                            <p>If you havn't got an account yet, please <a href="{% url 'account_signup' %}">Register</a></p>
                        </div>
                        {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>


<!-- Back button -->
<div class="row mt-5">
    <div class="col-2">
        <a href="{% url 'hotel:RoomListView' %}" class="btn btn-primary mb-2">Pick another room</a>
    </div>
</div>

{% endblock %}

templates/room_images.html
{% load static %}

{% if room_images == 'DUBBLE' %}
<img src="{% static 'media/LUXURY.jpg' %}" alt="" class="card-img-top">
{% endif %}

{% if room_images == 'SINGAL' %}
<img src="{% static 'media/LUXURY.jpg' %}" alt="" class="card-img-top">
{% endif %}

{% if room_images == 'LUXURY' %}
<img src="{% static 'media/LUXURY.jpg' %}" alt="" class="card-img-top">
{% endif %}

templates/room_information.html
{% load static %}

<!------------- LUXURY ------------->

{% if room_information == 'LUXURY' %}
<!-- Long Information -->
<p>LUXURY - Long information</p>
{% endif %}

{% if room_short_information == 'LUXURY' %}
<!-- Short information -->
<p class="text-center">Є95</p>
{% endif %}

<!------------- KING ------------->

{% if room_information == 'DUBBLE' %}
<!-- Long Information -->
<p>DUBBLE - Long information</p>
{% endif %}

{% if room_short_information == 'DUBBLE' %}
<!-- Short information -->
<p class="text-center">Є75</p>
{% endif %}

<!------------- QUEEN ------------->

{% if room_information == 'SINGAL' %}
<!-- Long Information -->
<p>SINGAL - Long information</p>
{% endif %}

{% if room_short_information == 'SINGAL' %}
<!-- Short information -->
<p class="text-center">Є45</p>
{% endif %}

templates/room_list.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
<h1>Room List</h1>
{% for room in room_list %}
<div class="col-md-4 mt-3">
    {% include 'card.html' %}
</div>
{% endfor %}
</div>

{% endblock %}

templates/room_list_view.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
    <div class="row justify-content-center card-push-down">
        {% for room_category, room_url in room_list %}
        <div class="col-md-4">
            <a href="{{ room_url }}">
                <div class="card border-5 border-light">
                    <div class="img-hover-zoom">
                        {% include 'room_images.html' with room_images=room_category %}
                    </div>
                    <!-- Card Title and Price -->
                    <h4 class="card-title text-center mt-1">{{ room_category }} Suite
                        {% include 'room_information.html' with room_short_information=room_category %}</h4>
                </div>
            </a>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/success_booking.html
{% extends 'base.html' %}
{% block content %}
<p>{{ booking }}</p>
<p>You have booked from {{ booking.check_in }} to {{ booking.check_out }}</p>

{% endblock %}